/* autogenerated by Processing revision 1283 on 2022-07-29 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class DvdLogoBounce extends PApplet {

PImage dvd;
int posX = 1, posY = 1, dirX = 2, dirY = 2;
int hue = 360;
final int imgW = 180, imgH = 85, winW = 1280, winH = 720;
boolean changeTint = false;

//Executed once (on startup)
 public void setup(){
  //Defining window size
  /* size commented out by preprocessor */;
  /* smooth commented out by preprocessor */;
  dvd = loadImage("dvd.png");
  colorMode(HSB, 360);
  println("Window created");
}

 public void draw(){
  background(0);
  
  image(dvd, posX, posY);
  
  if((posX + imgW) >= winW || posX <= 0){
    dirX *= -1;
    changeTint = true;
  }
    
    
  if((posY + imgH) >= winH || posY <= 0){
    dirY *= -1;
    changeTint = true;
  }
    
  if(changeTint){
    hue = (int)random(360);
    tint(hue,360,360);
    changeTint = false;
  }
  
  //Changing X and Y of the logo
  posX += dirX; 
  posY += dirY;
}


  public void settings() { size(1280, 720);
smooth(4); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "DvdLogoBounce" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
