/* autogenerated by Processing revision 1283 on 2022-07-29 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class LineDrawer extends PApplet {

int hue = 359;
int direction = -1;
boolean redDone = false, greenDone = false, blueDone = false;

 public void setup(){
  //Window size
  /* size commented out by preprocessor */;
  
  //Background color setup
  background(12);
  
  //Draw lines with anti-aliasing
  /* smooth commented out by preprocessor */;
  
  //Console print
  println("Window created");
  
  colorMode(HSB, 360);
}

 public void draw(){
  //Stroke color setup
  stroke(hue, 360, 360);
  
    
  //Checking whether mouse's left button is pressed 
  if(mousePressed){
    hue += direction;
    if(hue == 0 || hue >= 359)
      direction *= -1;
    println("hue = " + hue);
    
    //draw line
    line(mouseX, mouseY, pmouseX, pmouseY);
  }
}


  public void settings() { size(1280, 720);
smooth(); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "LineDrawer" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
