/* autogenerated by Processing revision 1283 on 2022-08-09 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class RotatingCube extends PApplet {

float rotation = 0, zPos;

 public void setup(){
  /* size commented out by preprocessor */;
  noFill();
  stroke(255);
  /* smooth commented out by preprocessor */;
}

 public void draw(){
  lights();
  translate(mouseX, mouseY, zPos); 
  background(16);
  rotateY(rotation);
  rotation += 0.05f;
  box(400);
}

 public void mousePressed(){
  if(mouseButton == LEFT)
  { fill(255); noStroke(); }
    
  else if(mouseButton == RIGHT)
  { noFill(); stroke(255); }
}

 public void mouseWheel(MouseEvent event) {
  // getCount() > 0 if moved backwards (towards the user), < 0 if moved forward (in the other direction) 
  float e = event.getCount();
  if(e > 0)
    zPos -= 20;
  else if (e < 0)
    zPos += 20;
}


  public void settings() { fullScreen(P3D);
smooth(4); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "RotatingCube" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
